<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>lu.kbra</groupId>
		<artifactId>model-exporter</artifactId>
		<version>${revision}</version>
		<relativePath>../model-exporter/</relativePath>
	</parent>

	<artifactId>image-exporter</artifactId>
	<packaging>pom</packaging>

	<name>Image Exporter Parent</name>

	<modules>
		<module>../image-exporter-png</module>
		<module>../image-exporter-svg</module>
		<module>../image-exporter-webp</module>
		<module>../image-exporter-tif</module>
		<module>../image-exporter-jpeg</module>
		<module>../image-exporter-bmp</module>
	</modules>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>lu.kbra</groupId>
				<artifactId>model-exporter-api</artifactId>
				<version>${revision}</version>
				<scope>provided</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>lu.kbra</groupId>
			<artifactId>model-exporter-api</artifactId>
		</dependency>
	</dependencies>

</project>