<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>lu.kbra</groupId>
		<artifactId>image-exporter</artifactId>
		<version>${revision}</version>
		<relativePath>../image-exporter</relativePath>
	</parent>

	<artifactId>image-exporter-bmp</artifactId>

	<name>Image Exporter BMP</name>

	<dependencies>
		<dependency>
			<groupId>com.twelvemonkeys.imageio</groupId>
			<artifactId>imageio-bmp</artifactId>
		</dependency>
	</dependencies>

</project>