app {
  name = "@conveyor.name@"
  version = "@appVersion@"
  fsname = "@conveyor.internal.name@"
  main-class = "@app.mainClass@"

  inputs += "@project.build.finalName@.jar"
}

input {
  main-jar = "@project.build.finalName@.jar"
}

java {
  runtime {
    modules = [ @conveyor.addModules@ ]
  }
}

metadata {
  vendor = "@conveyor.vendor@"
}

app {
  site.base-url = "@modelizer.website@"
  vcs-url = "@modelizer.repositoryUrl@"
}

conveyor {
  billing-email = "@conveyor.billingEmail@"
}


platform {
  windows {
    enable = @conveyor.windows@
  }
  linux {
    enable = @conveyor.linux@
  }
  mac {
    enable = @conveyor.macos@
  }
}

installers {
  windows {
    type = "@conveyor.windows.type@"
  }
  linux {
    type = "@conveyor.linux.type@"
  }
  mac {
    type = "@conveyor.macos.type@"
  }
}

app-image {
  enable = @conveyor.portable@
}

resources {
  icons = [ "@conveyor.icon@" ]
}