#!/bin/sh
set -e

APP_BIN_DIR="/opt/modelizer-next-app/bin"
TARGET="$APP_BIN_DIR/Modelizer Next App"
LINK="/usr/bin/modelizer-next-app"

if [ -x "$TARGET" ]; then
    ln -sfn "$TARGET" "$LINK"
fi

exit 0