name: Deploy Pages

on:
  workflow_dispatch: 
  push:
    branches:
      - pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
          set -e

          mkdir -p /var/www
          cd /var/www

          git config --global --add safe.directory /var/www/modelizer-next.kbra.lu
          if [ ! -d "modelizer-next.kbra.lu/.git" ]; then
            rm -rf modelizer-next.kbra.lu/*
            rm -rf modelizer-next.kbra.lu/.[!.]* modelizer-next.kbra.lu/..?* 2>/dev/null || true

            git clone \
              --branch pages \
              https://${{ secrets.GH_PAT }}@github.com/UnKabaraQuiDev/modelizer-next.git \
              "modelizer-next.kbra.lu"
          fi

          cd /var/www/modelizer-next.kbra.lu

          git fetch origin
          git checkout pages
          git reset --hard origin/pages
